baseURL = "https://pathologylab.ctl.columbia.edu/"
languageCode = "en-us"
title = "Pathology Lab Manual"
theme = "ctl-pathologylab"
googleAnalytics = "G-WQSHCJCX5Q"

[outputs]
  home = ["HTML","RSS", "JSON"]
